### ISSUE TITLE
Replace build dependency on libgnome-keyring by libsecret

### ISSUE THREAD

**Issue by sunweaver** [darkshram/seahorse-caja#6]
The GNOME people in Debian are asking for replacement of libgnome-keyring in caja-seahorse and use libsecret instead.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886476

They even started raising severity which threatens mate-power-manager to be auto-removed from Debian testing. Any porting work on this in sight?

If you have any questions or are in need of help, please contact the Debian+Ubuntu MATE Packaging Team on OFTC IRC (irc.debian.org, channel #debian-mate) or upstream MATE devs on Freenode IRC (channel: #mate-dev). Thanks!

**Comment by darkshram** [comment]
Ok. I'll start as soon as my work schedule allows it. Will try to do it myself, but guess l'll need help at some point if there is a deadline.

**Comment by darkshram** [comment]
Seems It's done in my test machine. There are no includes for libgnome-keyring, neither major code modifications were needed. Upstream code for latest stable (as you know seahorse-caja is a fork of seahorse-nautilus) just links to libgnome-keyring, but the only relevant code used to access the keyring is through gcr library. I'm going to do some more testing and review the code (after a quick review, seems nothing is really used to justify libgnome-keyring dependency). For the time being, just replaced the libgnome-keyring dependency with libsecret, but seems does not really use it either, because it works perfectly without any code modification.

Please, do me a favor and help me testing this patch.
[seahorse-caja-libsecret.zip](https://github.com/darkshram/seahorse-caja/files/1637912/seahorse-caja-libsecret.zip)

Tomorrow I'll do some extra testing removing libsecret and test if everything works. Recentely seahorse-nautilus migrated from autotools to meson, and current commit with meson config does not include any reference to libgnome-keyring or libsecret. So _seems_ libgnome-keyring dependency is just a left-over form earlier development.

If things work as I expect, will release 1.18.4 this week.

**Comment by darkshram** [comment]
Ok. I just did the test. libgnome-keyring is not used. It was a left-over from earlier development. So, just removed this dependecy. Code works fine. So, I'm releasing 1.18.4.

**Comment by sunweaver** [comment]
On  Fr 19 Jan 2018 00:59:48 CET, Joel Barrios wrote:

> Closed #6.

Thanks for this. Uploaded 1.18.4-1 to Debian unstable today.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
